module.exports = {
  'iconUpdateValidation': {
    'icon.item.download_url': 'required|string',
    'icon.item.format': 'required|string',
    'icon.item.preview_url': 'required|string',
    'icon.size': 'required|numeric',
    'field': 'required|string',
    'language': 'required|string'
  },
  'ourHistoryUpdateValidation': {
    'en.title': 'string',
    'en.subTitle': 'string',
    'en.description': 'string',
    'am.title': 'string',
    'am.subTitle': 'string',
    'am.description': 'string',
  },
  'infoValidation': {
    'en.phone.number': 'required|string',
    'en.phone.description': 'required|string',
    'en.phone.icon.item.download_url': 'required|string',
    'en.phone.icon.item.format': 'required|string',
    'en.phone.icon.item.preview_url': 'required|string',
    'en.phone.icon.size': 'required|numeric',
    'en.address.title': 'required|string',
    'en.address.description': 'required|string',
    'en.address.icon.item.format': 'required|string',
    'en.address.icon.item.preview_url': 'required|string',
    'en.address.icon.size': 'required|numeric',
    'en.workingHours.title': 'required|string',
    'en.workingHours.description': 'required|string',
    'en.workingHours.icon.item.format': 'required|string',
    'en.workingHours.icon.item.preview_url': 'required|string',
    'en.workingHours.icon.size': 'required|numeric',
    'am.phone.number': 'required|string',
    'am.phone.description': 'required|string',
    'am.phone.icon.item.download_url': 'required|string',
    'am.phone.icon.item.format': 'required|string',
    'am.phone.icon.item.preview_url': 'required|string',
    'am.phone.icon.size': 'required|numeric',
    'am.address.title': 'required|string',
    'am.address.description': 'required|string',
    'am.address.icon.item.download_url': 'required|string',
    'am.address.icon.item.format': 'required|string',
    'am.address.icon.item.preview_url': 'required|string',
    'am.address.icon.size': 'required|numeric',
    'am.workingHours.title': 'required|string',
    'am.workingHours.description': 'required|string',
    'am.workingHours.icon.item.download_url': 'required|string',
    'am.workingHours.icon.item.format': 'required|string',
    'am.workingHours.icon.item.preview_url': 'required|string',
    'am.workingHours.icon.size': 'required|numeric',
  }
};